### ISSUE TITLE
Library does not work with react-hook-form v7.55.0

### ISSUE THREAD

**Issue by cgero-eth** [react-hook-form/devtools#220]
When integrating `@hookform/devtools` with the latest version of `react-hook-form`, the application crashes with:

> control._updateValid is not a function

CodeSandbox: https://codesandbox.io/p/sandbox/nostalgic-scooby-jwlqtd

```
"@hookform/devtools": "4.3.3",
"react-hook-form": "7.55.0",
```

**Comment by gokulyc** [comment]
Same here. My project setup is Astro + ReactJS (With Vite).

**Comment by vhlongonPolestar** [comment]
same here, getting the erro `control._updateValid is not a function`

**Comment by bluebill1049** [comment]
thanks for reporting. I will fix it this week.

**Comment by code-with-von** [comment]
Same problem here... just to add more details, I'm getting here the error:

`**control._updateValid** is not a function`

![Image](https://github.com/user-attachments/assets/42be0e2d-c326-4cfc-8176-e05dc25a50f9)

**Comment by luisemz** [comment]
Same issue here, project setup: app router nextjs.

**Comment by nemonemi** [comment]
Hey @bluebill1049 , why was this ticket closed? I have managed to resolve it by downgrading from 7.56.3 to 7.53.0, but that should not be the solution.

**Comment by vonschappler** [comment]
> Hey [@bluebill1049](https://github.com/bluebill1049) , why was this ticket closed? I have managed to resolve it by downgrading from 7.56.3 to 7.53.0, but that should not be the solution.

They have released an update to `@hookform/devtools` (v4.4.0) which seems to have fixed the issue...
I'm using here:
```json
    "@hookform/devtools": "^4.4.0",
    "react-hook-form": "^7.56.3",
```
and it's working fine.

**Comment by vonschappler** [comment]
> This combination hasn't worked for me.

That combination is the latest version of both libs and it works fine here... I could advice you to double check your code, as i just had written a form here and I can say that it is working.
